// flow-typed signature: 0264b4413c0c47cad9dde240a2bda0a9
// flow-typed version: <<STUB>>/command-exists_v^1.2.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'command-exists'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'command-exists' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'command-exists/lib/command-exists' {
  declare module.exports: any;
}

declare module 'command-exists/test/executable-script' {
  declare module.exports: any;
}

declare module 'command-exists/test/non-executable-script' {
  declare module.exports: any;
}

declare module 'command-exists/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'command-exists/index' {
  declare module.exports: $Exports<'command-exists'>;
}
declare module 'command-exists/index.js' {
  declare module.exports: $Exports<'command-exists'>;
}
declare module 'command-exists/lib/command-exists.js' {
  declare module.exports: $Exports<'command-exists/lib/command-exists'>;
}
declare module 'command-exists/test/executable-script.js' {
  declare module.exports: $Exports<'command-exists/test/executable-script'>;
}
declare module 'command-exists/test/non-executable-script.js' {
  declare module.exports: $Exports<'command-exists/test/non-executable-script'>;
}
declare module 'command-exists/test/test.js' {
  declare module.exports: $Exports<'command-exists/test/test'>;
}
