// flow-typed signature: 489caaecb51a3d6995a4a7e91bd6ba2f
// flow-typed version: <<STUB>>/css-literal-loader_v^0.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-literal-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-literal-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-literal-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'css-literal-loader/lib/plugin' {
  declare module.exports: any;
}

declare module 'css-literal-loader/lib/proxyFileSystem' {
  declare module.exports: any;
}

declare module 'css-literal-loader/lib/traverse' {
  declare module.exports: any;
}

declare module 'css-literal-loader/lib/VirtualModulePlugin' {
  declare module.exports: any;
}

declare module 'css-literal-loader/lib/visitor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-literal-loader/lib/loader.js' {
  declare module.exports: $Exports<'css-literal-loader/lib/loader'>;
}
declare module 'css-literal-loader/lib/plugin.js' {
  declare module.exports: $Exports<'css-literal-loader/lib/plugin'>;
}
declare module 'css-literal-loader/lib/proxyFileSystem.js' {
  declare module.exports: $Exports<'css-literal-loader/lib/proxyFileSystem'>;
}
declare module 'css-literal-loader/lib/traverse.js' {
  declare module.exports: $Exports<'css-literal-loader/lib/traverse'>;
}
declare module 'css-literal-loader/lib/VirtualModulePlugin.js' {
  declare module.exports: $Exports<'css-literal-loader/lib/VirtualModulePlugin'>;
}
declare module 'css-literal-loader/lib/visitor.js' {
  declare module.exports: $Exports<'css-literal-loader/lib/visitor'>;
}
