// flow-typed signature: f94fc5a768574031ab73c256ede23908
// flow-typed version: <<STUB>>/eslint-config-satya164_v^1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-satya164'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-satya164' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-satya164/index' {
  declare module.exports: $Exports<'eslint-config-satya164'>;
}
declare module 'eslint-config-satya164/index.js' {
  declare module.exports: $Exports<'eslint-config-satya164'>;
}
