// flow-typed signature: 880975ac525acb773150a74cb38de94e
// flow-typed version: <<STUB>>/eventsource_v^1.0.5/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eventsource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eventsource' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eventsource/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'eventsource/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'eventsource/coverage/prettify' {
  declare module.exports: any;
}

declare module 'eventsource/coverage/sorter' {
  declare module.exports: any;
}

declare module 'eventsource/example/eventsource-polyfill' {
  declare module.exports: any;
}

declare module 'eventsource/example/sse-client' {
  declare module.exports: any;
}

declare module 'eventsource/example/sse-server' {
  declare module.exports: any;
}

declare module 'eventsource/lib/eventsource-polyfill' {
  declare module.exports: any;
}

declare module 'eventsource/lib/eventsource' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eventsource/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'eventsource/coverage/lcov-report/prettify'>;
}
declare module 'eventsource/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'eventsource/coverage/lcov-report/sorter'>;
}
declare module 'eventsource/coverage/prettify.js' {
  declare module.exports: $Exports<'eventsource/coverage/prettify'>;
}
declare module 'eventsource/coverage/sorter.js' {
  declare module.exports: $Exports<'eventsource/coverage/sorter'>;
}
declare module 'eventsource/example/eventsource-polyfill.js' {
  declare module.exports: $Exports<'eventsource/example/eventsource-polyfill'>;
}
declare module 'eventsource/example/sse-client.js' {
  declare module.exports: $Exports<'eventsource/example/sse-client'>;
}
declare module 'eventsource/example/sse-server.js' {
  declare module.exports: $Exports<'eventsource/example/sse-server'>;
}
declare module 'eventsource/lib/eventsource-polyfill.js' {
  declare module.exports: $Exports<'eventsource/lib/eventsource-polyfill'>;
}
declare module 'eventsource/lib/eventsource.js' {
  declare module.exports: $Exports<'eventsource/lib/eventsource'>;
}
