// flow-typed signature: b776f9a7bd3899372ba465811cd185f1
// flow-typed version: <<STUB>>/glob-expand_v^0.2.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glob-expand'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glob-expand' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glob-expand/build/code/expand' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glob-expand/build/code/expand.js' {
  declare module.exports: $Exports<'glob-expand/build/code/expand'>;
}
