// flow-typed signature: e62b6f957029c33088c9ee616beba56f
// flow-typed version: <<STUB>>/koa-webpack_v^1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-webpack/dist/index' {
  declare module.exports: any;
}

declare module 'koa-webpack/test/fixtures/input' {
  declare module.exports: any;
}

declare module 'koa-webpack/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-webpack/dist/index.js' {
  declare module.exports: $Exports<'koa-webpack/dist/index'>;
}
declare module 'koa-webpack/index' {
  declare module.exports: $Exports<'koa-webpack'>;
}
declare module 'koa-webpack/index.js' {
  declare module.exports: $Exports<'koa-webpack'>;
}
declare module 'koa-webpack/test/fixtures/input.js' {
  declare module.exports: $Exports<'koa-webpack/test/fixtures/input'>;
}
declare module 'koa-webpack/test/index.js' {
  declare module.exports: $Exports<'koa-webpack/test/index'>;
}
