// flow-typed signature: 504c9941aed37a68e193df77d733d462
// flow-typed version: <<STUB>>/koa-webpack_v^0.3.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-webpack/dist/index' {
  declare module.exports: any;
}

declare module 'koa-webpack/gulpfile.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-webpack/dist/index.js' {
  declare module.exports: $Exports<'koa-webpack/dist/index'>;
}
declare module 'koa-webpack/gulpfile.babel.js' {
  declare module.exports: $Exports<'koa-webpack/gulpfile.babel'>;
}
declare module 'koa-webpack/index' {
  declare module.exports: $Exports<'koa-webpack'>;
}
declare module 'koa-webpack/index.js' {
  declare module.exports: $Exports<'koa-webpack'>;
}
