// flow-typed signature: 3f0347b7117390a18746252c876e972e
// flow-typed version: <<STUB>>/koa_v^2.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa/lib/application' {
  declare module.exports: any;
}

declare module 'koa/lib/context' {
  declare module.exports: any;
}

declare module 'koa/lib/request' {
  declare module.exports: any;
}

declare module 'koa/lib/response' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa/lib/application.js' {
  declare module.exports: $Exports<'koa/lib/application'>;
}
declare module 'koa/lib/context.js' {
  declare module.exports: $Exports<'koa/lib/context'>;
}
declare module 'koa/lib/request.js' {
  declare module.exports: $Exports<'koa/lib/request'>;
}
declare module 'koa/lib/response.js' {
  declare module.exports: $Exports<'koa/lib/response'>;
}
